services:
  mongo:
    image: mongo
    container_name: mongo
    ports:
      - '27017:27017'

  backend:
    build: ./backend
    container_name: backend
    ports:
      - '4444:3000'
    environment:
      - MONGO_URL=mongodb://mongo:27017
      - DB_NAME=qurl
      - BASE_URL=http://localhost:4444  # Adjusted to use port 4444

  frontend:
    build: ./frontend
    container_name: frontend
    ports:
      - '4443:3000'  # Map internal port 3000 to external port 4443
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:4444
    depends_on:
      - backend
